// templates/react-ts.webapp/src/tech/Tech.ts
import React, {Component} from "react";
import axios from "axios";
import "./Tech.css"

export class Tech extends Component {
    state = {
        technologies: []
    };

    componentDidMount() {
        axios.get(`${process.env.REACT_APP_API_URL}/api/technologies`)
            .then(resp => this.setState({
                technologies: resp.data
            }));
    }

    render() {
        const technologies = this.state.technologies.map((technology, i) =>
            <li key={i}>
                <b>{technology.name}</b>: {technology.details}
            </li>
        );
        return (
            <ul className="technologies">
                {technologies}
            </ul>
        );
    }
}

// templates/vue.webapp/src/components/Tech.vue
<template>
  <ul class="technologies">
    <li v-for="technology in technologies" v-bind:key="technology.name">
      <b>{{technology.name}}</b>: {{technology.details}}
    </li>
  </ul>
</template>

<script>
import axios from 'axios'

export default {
  name: 'Tech',
  data() {
    return {
      technologies: []
    };
  },
  mounted() {
    axios
      .get(`${process.env.VUE_APP_API_URL}/api/technologies`)
      .then(response => (this.technologies = response.data));
  }
};
</script>

<style scoped>
.technologies {
  margin-top: 5px;
}
</style>
